import { BarChartIcon, ClipboardCheckIcon, HistoryIcon, LayoutDashboardIcon, ReceiptTextIcon, UsersIcon } from 'lucide-react'
import { ROUTES } from '@/config/routes'
import type { AppPage } from './app-page.types'

export const ADMIN_PAGES: readonly AppPage[] = [
  {
    id: 'admin',
    path: ROUTES.admin,
    icon: LayoutDashboardIcon,
    roles: ['ADMIN', 'SUPER_ADMIN'],
    showInSidebar: true,
    lazy: async () => ({ Component: (await import('@/features/admin/pages/AdminPage')).AdminPage }),
  },
  {
    id: 'statistics',
    path: ROUTES.statistics,
    icon: BarChartIcon,
    roles: ['ADMIN', 'SUPER_ADMIN'],
    permission: 'STATISTICS_VIEW',
    showInSidebar: true,
    lazy: async () => ({ Component: (await import('@/features/admin/pages/StatisticsPage')).StatisticsPage }),
  },
  {
    id: 'kycReviews',
    path: ROUTES.kycReviews,
    icon: ClipboardCheckIcon,
    roles: ['ADMIN', 'SUPER_ADMIN'],
    permission: 'KYC_REVIEW',
    showInSidebar: true,
    lazy: async () => ({ Component: (await import('@/features/kyc-review/pages/KycReviewsPage')).KycReviewsPage }),
  },
  {
    id: 'kycReview',
    path: ROUTES.kycReview,
    icon: ClipboardCheckIcon,
    roles: ['ADMIN', 'SUPER_ADMIN'],
    permission: 'KYC_REVIEW',
    parentId: 'kycReviews',
    showInSidebar: false,
    lazy: async () => ({ Component: (await import('@/features/kyc-review/pages/KycReviewPage')).KycReviewPage }),
  },
  {
    id: 'users',
    path: ROUTES.users,
    icon: UsersIcon,
    roles: ['ADMIN', 'SUPER_ADMIN'],
    permission: 'USER_MANAGE',
    showInSidebar: true,
    lazy: async () => ({ Component: (await import('@/features/user-management/pages/UsersPage')).UsersPage }),
  },
  {
    id: 'userCreate',
    path: ROUTES.userCreate,
    icon: UsersIcon,
    roles: ['ADMIN', 'SUPER_ADMIN'],
    permission: 'USER_MANAGE',
    parentId: 'users',
    showInSidebar: false,
    lazy: async () => ({ Component: (await import('@/features/user-management/pages/CreateUserPage')).CreateUserPage }),
  },
  {
    id: 'user',
    path: ROUTES.user,
    icon: UsersIcon,
    roles: ['ADMIN', 'SUPER_ADMIN'],
    permission: 'USER_MANAGE',
    parentId: 'users',
    showInSidebar: false,
    lazy: async () => ({ Component: (await import('@/features/user-management/pages/UserDetailPage')).UserDetailPage }),
  },
  {
    id: 'userTransactions',
    path: ROUTES.userTransactions,
    icon: ReceiptTextIcon,
    roles: ['ADMIN', 'SUPER_ADMIN'],
    permission: 'USER_MANAGE',
    parentId: 'users',
    showInSidebar: false,
    lazy: async () => ({ Component: (await import('@/features/user-management/pages/UserTransactionsPage')).UserTransactionsPage }),
  },
  {
    id: 'auditLog',
    path: ROUTES.auditLog,
    icon: HistoryIcon,
    roles: ['SUPER_ADMIN'],
    showInSidebar: true,
    lazy: async () => ({ Component: (await import('@/features/audit-log/pages/AuditLogPage')).AuditLogPage }),
  },
]
