export const ROUTES = {
  root: '/',
  login: '/login',
  register: '/register',
  verifyEmail: '/verify-email',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  changePassword: '/account/password',
  profile: '/account/profile',
  wallet: '/wallet',
  transactions: '/transactions',
  verification: '/verification',
  merchant: '/merchant',
  merchantPayments: '/merchant/payments',
  merchantApiKeys: '/merchant/api-keys',
  checkout: '/checkout/:sessionId',
  admin: '/admin',
  kycReviews: '/admin/kyc',
  kycReview: '/admin/kyc/:applicationId',
  users: '/admin/users',
  userCreate: '/admin/users/new',
  user: '/admin/users/:userId',
  userTransactions: '/admin/users/:userId/transactions',
  auditLog: '/admin/audit-log',
  paymentRequests: '/payment-requests',
} as const
