export const ROUTES = {
  root: '/',
  login: '/login',
  register: '/register',
  verifyEmail: '/verify-email',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  changePassword: '/account/password',
  wallet: '/wallet',
  transactions: '/transactions',
  verification: '/verification',
  merchant: '/merchant',
  admin: '/admin',
  kycReviews: '/admin/kyc',
  kycReview: '/admin/kyc/:applicationId',
  users: '/admin/users',
  userCreate: '/admin/users/new',
  user: '/admin/users/:userId',
  auditLog: '/admin/audit-log',
} as const